version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - npm install -g yarn
      # Install dependencies needed for running tests
      - yarn install
